// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coordinator.sql

package dbquery

import (
	"context"
)

const coordinatorCooldowns = `-- name: CoordinatorCooldowns :many
SELECT identity_id, route_key, status, reason, expires_at
FROM cooldowns
WHERE expires_at > ?
ORDER BY expires_at
`

func (q *Queries) CoordinatorCooldowns(ctx context.Context, expiresAt int64) ([]Cooldown, error) {
	rows, err := q.db.QueryContext(ctx, coordinatorCooldowns, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cooldown
	for rows.Next() {
		var i Cooldown
		if err := rows.Scan(
			&i.IdentityID,
			&i.RouteKey,
			&i.Status,
			&i.Reason,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const coordinatorLeases = `-- name: CoordinatorLeases :many
SELECT route_key, identity_id, expires_at
FROM leases
WHERE expires_at > ?
ORDER BY expires_at
`

func (q *Queries) CoordinatorLeases(ctx context.Context, expiresAt int64) ([]Lease, error) {
	rows, err := q.db.QueryContext(ctx, coordinatorLeases, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lease
	for rows.Next() {
		var i Lease
		if err := rows.Scan(&i.RouteKey, &i.IdentityID, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const coordinatorRates = `-- name: CoordinatorRates :many
SELECT identity_id, resource, remaining, reset_at
FROM rate_states
WHERE reset_at > ?
ORDER BY identity_id, resource
`

func (q *Queries) CoordinatorRates(ctx context.Context, resetAt int64) ([]RateState, error) {
	rows, err := q.db.QueryContext(ctx, coordinatorRates, resetAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RateState
	for rows.Next() {
		var i RateState
		if err := rows.Scan(
			&i.IdentityID,
			&i.Resource,
			&i.Remaining,
			&i.ResetAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCooldownsTable = `-- name: CreateCooldownsTable :exec
CREATE TABLE IF NOT EXISTS cooldowns (
  identity_id TEXT NOT NULL,
  route_key TEXT NOT NULL,
  status INTEGER NOT NULL,
  reason TEXT NOT NULL,
  expires_at INTEGER NOT NULL,
  PRIMARY KEY (identity_id, route_key)
)
`

func (q *Queries) CreateCooldownsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createCooldownsTable)
	return err
}

const createLeasesTable = `-- name: CreateLeasesTable :exec
CREATE TABLE IF NOT EXISTS leases (
  route_key TEXT PRIMARY KEY,
  identity_id TEXT NOT NULL,
  expires_at INTEGER NOT NULL
)
`

func (q *Queries) CreateLeasesTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createLeasesTable)
	return err
}

const createRateStatesTable = `-- name: CreateRateStatesTable :exec
CREATE TABLE IF NOT EXISTS rate_states (
  identity_id TEXT NOT NULL,
  resource TEXT NOT NULL,
  remaining INTEGER NOT NULL,
  reset_at INTEGER NOT NULL,
  PRIMARY KEY (identity_id, resource)
)
`

func (q *Queries) CreateRateStatesTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createRateStatesTable)
	return err
}

const getCooldownExpiresAt = `-- name: GetCooldownExpiresAt :one
SELECT expires_at
FROM cooldowns
WHERE identity_id = ?
  AND route_key = ?
`

type GetCooldownExpiresAtParams struct {
	IdentityID string `json:"identity_id"`
	RouteKey   string `json:"route_key"`
}

func (q *Queries) GetCooldownExpiresAt(ctx context.Context, arg GetCooldownExpiresAtParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCooldownExpiresAt, arg.IdentityID, arg.RouteKey)
	var expires_at int64
	err := row.Scan(&expires_at)
	return expires_at, err
}

const getLease = `-- name: GetLease :one
SELECT identity_id, expires_at
FROM leases
WHERE route_key = ?
`

type GetLeaseRow struct {
	IdentityID string `json:"identity_id"`
	ExpiresAt  int64  `json:"expires_at"`
}

func (q *Queries) GetLease(ctx context.Context, routeKey string) (GetLeaseRow, error) {
	row := q.db.QueryRowContext(ctx, getLease, routeKey)
	var i GetLeaseRow
	err := row.Scan(&i.IdentityID, &i.ExpiresAt)
	return i, err
}

const getRateState = `-- name: GetRateState :one
SELECT remaining, reset_at
FROM rate_states
WHERE identity_id = ?
  AND resource = ?
`

type GetRateStateParams struct {
	IdentityID string `json:"identity_id"`
	Resource   string `json:"resource"`
}

type GetRateStateRow struct {
	Remaining int64 `json:"remaining"`
	ResetAt   int64 `json:"reset_at"`
}

func (q *Queries) GetRateState(ctx context.Context, arg GetRateStateParams) (GetRateStateRow, error) {
	row := q.db.QueryRowContext(ctx, getRateState, arg.IdentityID, arg.Resource)
	var i GetRateStateRow
	err := row.Scan(&i.Remaining, &i.ResetAt)
	return i, err
}

const upsertCooldown = `-- name: UpsertCooldown :exec
INSERT INTO cooldowns (identity_id, route_key, status, reason, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(identity_id, route_key) DO UPDATE SET
  status = excluded.status,
  reason = excluded.reason,
  expires_at = excluded.expires_at
`

type UpsertCooldownParams struct {
	IdentityID string `json:"identity_id"`
	RouteKey   string `json:"route_key"`
	Status     int64  `json:"status"`
	Reason     string `json:"reason"`
	ExpiresAt  int64  `json:"expires_at"`
}

func (q *Queries) UpsertCooldown(ctx context.Context, arg UpsertCooldownParams) error {
	_, err := q.db.ExecContext(ctx, upsertCooldown,
		arg.IdentityID,
		arg.RouteKey,
		arg.Status,
		arg.Reason,
		arg.ExpiresAt,
	)
	return err
}

const upsertLease = `-- name: UpsertLease :exec
INSERT INTO leases (route_key, identity_id, expires_at)
VALUES (?1, ?2, ?3)
ON CONFLICT(route_key) DO UPDATE SET
  identity_id = excluded.identity_id,
  expires_at = excluded.expires_at
`

type UpsertLeaseParams struct {
	RouteKey   string `json:"route_key"`
	IdentityID string `json:"identity_id"`
	ExpiresAt  int64  `json:"expires_at"`
}

func (q *Queries) UpsertLease(ctx context.Context, arg UpsertLeaseParams) error {
	_, err := q.db.ExecContext(ctx, upsertLease, arg.RouteKey, arg.IdentityID, arg.ExpiresAt)
	return err
}

const upsertRateState = `-- name: UpsertRateState :exec
INSERT INTO rate_states (identity_id, resource, remaining, reset_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(identity_id, resource) DO UPDATE SET
  remaining = excluded.remaining,
  reset_at = excluded.reset_at
`

type UpsertRateStateParams struct {
	IdentityID string `json:"identity_id"`
	Resource   string `json:"resource"`
	Remaining  int64  `json:"remaining"`
	ResetAt    int64  `json:"reset_at"`
}

func (q *Queries) UpsertRateState(ctx context.Context, arg UpsertRateStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertRateState,
		arg.IdentityID,
		arg.Resource,
		arg.Remaining,
		arg.ResetAt,
	)
	return err
}
