// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: d1.sql

package dbquery

import (
	"context"
	"database/sql"
)

const authenticateCaller = `-- name: AuthenticateCaller :one
SELECT callers.id, callers.name, callers.github_login, callers.org_login, callers.org_verified_at
FROM callers
JOIN caller_pools ON caller_pools.caller_id = callers.id
WHERE callers.token_hash = ?1
  AND callers.status = 'active'
  AND caller_pools.pool_id = ?2
LIMIT 1
`

type AuthenticateCallerParams struct {
	TokenHash string `json:"token_hash"`
	PoolID    string `json:"pool_id"`
}

type AuthenticateCallerRow struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	GithubLogin   string         `json:"github_login"`
	OrgLogin      string         `json:"org_login"`
	OrgVerifiedAt sql.NullString `json:"org_verified_at"`
}

func (q *Queries) AuthenticateCaller(ctx context.Context, arg AuthenticateCallerParams) (AuthenticateCallerRow, error) {
	row := q.db.QueryRowContext(ctx, authenticateCaller, arg.TokenHash, arg.PoolID)
	var i AuthenticateCallerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GithubLogin,
		&i.OrgLogin,
		&i.OrgVerifiedAt,
	)
	return i, err
}

const coveringPublicRepoProof = `-- name: CoveringPublicRepoProof :one
SELECT 1
FROM github_public_repos
WHERE lower(owner) = ?1
  AND lower(repo) = ?2
  AND checked_at >= datetime(?3, '-5 seconds')
LIMIT 1
`

type CoveringPublicRepoProofParams struct {
	Owner    string      `json:"owner"`
	Repo     string      `json:"repo"`
	Datetime interface{} `json:"datetime"`
}

func (q *Queries) CoveringPublicRepoProof(ctx context.Context, arg CoveringPublicRepoProofParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, coveringPublicRepoProof, arg.Owner, arg.Repo, arg.Datetime)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const dashboardCache = `-- name: DashboardCache :one
SELECT
  COUNT(*) AS total_entries,
  SUM(CASE WHEN expires_at > CURRENT_TIMESTAMP THEN 1 ELSE 0 END) AS fresh_entries,
  SUM(CASE WHEN expires_at <= CURRENT_TIMESTAMP THEN 1 ELSE 0 END) AS expired_entries,
  COALESCE(SUM(length(body_json)), 0) AS body_bytes,
  MIN(created_at) AS oldest_created_at,
  MAX(created_at) AS newest_created_at
FROM github_cache_entries
WHERE pool_id = ?1
`

type DashboardCacheRow struct {
	TotalEntries    int64           `json:"total_entries"`
	FreshEntries    sql.NullFloat64 `json:"fresh_entries"`
	ExpiredEntries  sql.NullFloat64 `json:"expired_entries"`
	BodyBytes       interface{}     `json:"body_bytes"`
	OldestCreatedAt interface{}     `json:"oldest_created_at"`
	NewestCreatedAt interface{}     `json:"newest_created_at"`
}

func (q *Queries) DashboardCache(ctx context.Context, poolID string) (DashboardCacheRow, error) {
	row := q.db.QueryRowContext(ctx, dashboardCache, poolID)
	var i DashboardCacheRow
	err := row.Scan(
		&i.TotalEntries,
		&i.FreshEntries,
		&i.ExpiredEntries,
		&i.BodyBytes,
		&i.OldestCreatedAt,
		&i.NewestCreatedAt,
	)
	return i, err
}

const dashboardCacheRoutes = `-- name: DashboardCacheRoutes :many
SELECT
  route_kind,
  COUNT(*) AS entries,
  SUM(CASE WHEN expires_at > CURRENT_TIMESTAMP THEN 1 ELSE 0 END) AS fresh_entries,
  MAX(created_at) AS latest_created_at
FROM github_cache_entries
WHERE pool_id = ?1
GROUP BY route_kind
ORDER BY entries DESC, route_kind
LIMIT 12
`

type DashboardCacheRoutesRow struct {
	RouteKind       string          `json:"route_kind"`
	Entries         int64           `json:"entries"`
	FreshEntries    sql.NullFloat64 `json:"fresh_entries"`
	LatestCreatedAt interface{}     `json:"latest_created_at"`
}

func (q *Queries) DashboardCacheRoutes(ctx context.Context, poolID string) ([]DashboardCacheRoutesRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardCacheRoutes, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardCacheRoutesRow
	for rows.Next() {
		var i DashboardCacheRoutesRow
		if err := rows.Scan(
			&i.RouteKind,
			&i.Entries,
			&i.FreshEntries,
			&i.LatestCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardIdentities = `-- name: DashboardIdentities :many
SELECT id, kind, login, installation_id, status, weight, updated_at
FROM identities
WHERE pool_id = ?1
ORDER BY status = 'active' DESC, weight DESC, id
`

type DashboardIdentitiesRow struct {
	ID             string        `json:"id"`
	Kind           string        `json:"kind"`
	Login          string        `json:"login"`
	InstallationID sql.NullInt64 `json:"installation_id"`
	Status         string        `json:"status"`
	Weight         int64         `json:"weight"`
	UpdatedAt      string        `json:"updated_at"`
}

func (q *Queries) DashboardIdentities(ctx context.Context, poolID string) ([]DashboardIdentitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardIdentities, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardIdentitiesRow
	for rows.Next() {
		var i DashboardIdentitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Login,
			&i.InstallationID,
			&i.Status,
			&i.Weight,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardIdentityUsage = `-- name: DashboardIdentityUsage :many
SELECT identity_id, COUNT(*) AS requests, SUM(CASE WHEN status >= 400 THEN 1 ELSE 0 END) AS errors
FROM audit_events
WHERE pool_id = ?1
  AND created_at >= datetime('now', '-24 hours')
  AND identity_id IS NOT NULL
GROUP BY identity_id
ORDER BY requests DESC
LIMIT 20
`

type DashboardIdentityUsageRow struct {
	IdentityID sql.NullString  `json:"identity_id"`
	Requests   int64           `json:"requests"`
	Errors     sql.NullFloat64 `json:"errors"`
}

func (q *Queries) DashboardIdentityUsage(ctx context.Context, poolID string) ([]DashboardIdentityUsageRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardIdentityUsage, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardIdentityUsageRow
	for rows.Next() {
		var i DashboardIdentityUsageRow
		if err := rows.Scan(&i.IdentityID, &i.Requests, &i.Errors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardPublicRepos = `-- name: DashboardPublicRepos :one
SELECT
  COUNT(*) AS total_entries,
  SUM(CASE WHEN expires_at > CURRENT_TIMESTAMP THEN 1 ELSE 0 END) AS fresh_entries,
  MAX(checked_at) AS newest_checked_at
FROM github_public_repos
`

type DashboardPublicReposRow struct {
	TotalEntries    int64           `json:"total_entries"`
	FreshEntries    sql.NullFloat64 `json:"fresh_entries"`
	NewestCheckedAt interface{}     `json:"newest_checked_at"`
}

func (q *Queries) DashboardPublicRepos(ctx context.Context) (DashboardPublicReposRow, error) {
	row := q.db.QueryRowContext(ctx, dashboardPublicRepos)
	var i DashboardPublicReposRow
	err := row.Scan(&i.TotalEntries, &i.FreshEntries, &i.NewestCheckedAt)
	return i, err
}

const dashboardRecent = `-- name: DashboardRecent :many
SELECT
  audit_events.created_at,
  callers.github_login,
  audit_events.route_kind,
  audit_events.route_key,
  audit_events.identity_id,
  audit_events.status,
  audit_events.error_code,
  audit_events.duration_ms
FROM audit_events
JOIN callers ON callers.id = audit_events.caller_id
WHERE audit_events.pool_id = ?1
ORDER BY audit_events.created_at DESC
LIMIT 20
`

type DashboardRecentRow struct {
	CreatedAt   string         `json:"created_at"`
	GithubLogin string         `json:"github_login"`
	RouteKind   string         `json:"route_kind"`
	RouteKey    string         `json:"route_key"`
	IdentityID  sql.NullString `json:"identity_id"`
	Status      int64          `json:"status"`
	ErrorCode   sql.NullString `json:"error_code"`
	DurationMs  int64          `json:"duration_ms"`
}

func (q *Queries) DashboardRecent(ctx context.Context, poolID string) ([]DashboardRecentRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardRecent, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardRecentRow
	for rows.Next() {
		var i DashboardRecentRow
		if err := rows.Scan(
			&i.CreatedAt,
			&i.GithubLogin,
			&i.RouteKind,
			&i.RouteKey,
			&i.IdentityID,
			&i.Status,
			&i.ErrorCode,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRouteUsage = `-- name: DashboardRouteUsage :many
SELECT
  route_kind,
  COUNT(*) AS requests,
  SUM(CASE WHEN status >= 400 THEN 1 ELSE 0 END) AS errors,
  SUM(CASE WHEN cache_status = 'hit' THEN 1 ELSE 0 END) AS cache_hits,
  SUM(CASE WHEN cache_status = 'miss' THEN 1 ELSE 0 END) AS cache_misses,
  SUM(CASE WHEN cache_status = 'bypass' THEN 1 ELSE 0 END) AS cache_bypass
FROM audit_events
WHERE pool_id = ?1
  AND created_at >= datetime('now', '-24 hours')
GROUP BY route_kind
ORDER BY requests DESC
LIMIT 12
`

type DashboardRouteUsageRow struct {
	RouteKind   string          `json:"route_kind"`
	Requests    int64           `json:"requests"`
	Errors      sql.NullFloat64 `json:"errors"`
	CacheHits   sql.NullFloat64 `json:"cache_hits"`
	CacheMisses sql.NullFloat64 `json:"cache_misses"`
	CacheBypass sql.NullFloat64 `json:"cache_bypass"`
}

func (q *Queries) DashboardRouteUsage(ctx context.Context, poolID string) ([]DashboardRouteUsageRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardRouteUsage, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardRouteUsageRow
	for rows.Next() {
		var i DashboardRouteUsageRow
		if err := rows.Scan(
			&i.RouteKind,
			&i.Requests,
			&i.Errors,
			&i.CacheHits,
			&i.CacheMisses,
			&i.CacheBypass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardUsage = `-- name: DashboardUsage :one
SELECT
  COUNT(*) AS requests_24h,
  SUM(CASE WHEN status >= 400 THEN 1 ELSE 0 END) AS errors_24h,
  SUM(CASE WHEN cache_status = 'hit' THEN 1 ELSE 0 END) AS cache_hits_24h,
  SUM(CASE WHEN cache_status = 'miss' THEN 1 ELSE 0 END) AS cache_misses_24h,
  SUM(CASE WHEN cache_status = 'bypass' THEN 1 ELSE 0 END) AS cache_bypass_24h,
  AVG(duration_ms) AS avg_duration_ms_24h,
  MAX(created_at) AS latest_seen_at
FROM audit_events
WHERE pool_id = ?1
  AND created_at >= datetime('now', '-24 hours')
`

type DashboardUsageRow struct {
	Requests24h      int64           `json:"requests_24h"`
	Errors24h        sql.NullFloat64 `json:"errors_24h"`
	CacheHits24h     sql.NullFloat64 `json:"cache_hits_24h"`
	CacheMisses24h   sql.NullFloat64 `json:"cache_misses_24h"`
	CacheBypass24h   sql.NullFloat64 `json:"cache_bypass_24h"`
	AvgDurationMs24h sql.NullFloat64 `json:"avg_duration_ms_24h"`
	LatestSeenAt     interface{}     `json:"latest_seen_at"`
}

func (q *Queries) DashboardUsage(ctx context.Context, poolID string) (DashboardUsageRow, error) {
	row := q.db.QueryRowContext(ctx, dashboardUsage, poolID)
	var i DashboardUsageRow
	err := row.Scan(
		&i.Requests24h,
		&i.Errors24h,
		&i.CacheHits24h,
		&i.CacheMisses24h,
		&i.CacheBypass24h,
		&i.AvgDurationMs24h,
		&i.LatestSeenAt,
	)
	return i, err
}

const dashboardUsers = `-- name: DashboardUsers :many
SELECT
  callers.id,
  callers.name,
  callers.github_login,
  COUNT(*) AS requests,
  SUM(CASE WHEN audit_events.status >= 400 THEN 1 ELSE 0 END) AS errors,
  AVG(audit_events.duration_ms) AS avg_duration_ms,
  MAX(audit_events.created_at) AS last_seen
FROM audit_events
JOIN callers ON callers.id = audit_events.caller_id
WHERE audit_events.pool_id = ?1
  AND audit_events.created_at >= datetime('now', '-7 days')
GROUP BY callers.id, callers.name, callers.github_login
ORDER BY requests DESC, last_seen DESC
LIMIT 20
`

type DashboardUsersRow struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	GithubLogin   string          `json:"github_login"`
	Requests      int64           `json:"requests"`
	Errors        sql.NullFloat64 `json:"errors"`
	AvgDurationMs sql.NullFloat64 `json:"avg_duration_ms"`
	LastSeen      interface{}     `json:"last_seen"`
}

func (q *Queries) DashboardUsers(ctx context.Context, poolID string) ([]DashboardUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardUsers, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardUsersRow
	for rows.Next() {
		var i DashboardUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GithubLogin,
			&i.Requests,
			&i.Errors,
			&i.AvgDurationMs,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteIdentityScopes = `-- name: DeleteIdentityScopes :exec
DELETE FROM identity_scopes
WHERE identity_id = ?1
`

func (q *Queries) DeleteIdentityScopes(ctx context.Context, identityID string) error {
	_, err := q.db.ExecContext(ctx, deleteIdentityScopes, identityID)
	return err
}

const deleteOAuthStateAndExpired = `-- name: DeleteOAuthStateAndExpired :exec
DELETE FROM oauth_states
WHERE state_hash = ?1
   OR expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) DeleteOAuthStateAndExpired(ctx context.Context, stateHash string) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthStateAndExpired, stateHash)
	return err
}

const deleteWebSession = `-- name: DeleteWebSession :exec
DELETE FROM web_sessions
WHERE session_hash = ?1
`

func (q *Queries) DeleteWebSession(ctx context.Context, sessionHash string) error {
	_, err := q.db.ExecContext(ctx, deleteWebSession, sessionHash)
	return err
}

const ensurePool = `-- name: EnsurePool :exec
INSERT INTO pools (id, name, policy_json)
VALUES (?1, ?1, ?2)
ON CONFLICT(id) DO NOTHING
`

type EnsurePoolParams struct {
	ID         string `json:"id"`
	PolicyJson string `json:"policy_json"`
}

func (q *Queries) EnsurePool(ctx context.Context, arg EnsurePoolParams) error {
	_, err := q.db.ExecContext(ctx, ensurePool, arg.ID, arg.PolicyJson)
	return err
}

const freshCoveringPublicRepoProof = `-- name: FreshCoveringPublicRepoProof :one
SELECT 1
FROM github_public_repos
WHERE lower(owner) = ?1
  AND lower(repo) = ?2
  AND checked_at >= datetime(?3, '-5 seconds')
  AND expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

type FreshCoveringPublicRepoProofParams struct {
	Owner    string      `json:"owner"`
	Repo     string      `json:"repo"`
	Datetime interface{} `json:"datetime"`
}

func (q *Queries) FreshCoveringPublicRepoProof(ctx context.Context, arg FreshCoveringPublicRepoProofParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, freshCoveringPublicRepoProof, arg.Owner, arg.Repo, arg.Datetime)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const freshPublicRepoProof = `-- name: FreshPublicRepoProof :one
SELECT 1
FROM github_public_repos
WHERE lower(owner) = ?1
  AND lower(repo) = ?2
  AND expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

type FreshPublicRepoProofParams struct {
	Owner string `json:"owner"`
	Repo  string `json:"repo"`
}

func (q *Queries) FreshPublicRepoProof(ctx context.Context, arg FreshPublicRepoProofParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, freshPublicRepoProof, arg.Owner, arg.Repo)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getCallerPoolGrant = `-- name: GetCallerPoolGrant :one
SELECT 1
FROM caller_pools
WHERE caller_id = ?1
  AND pool_id = ?2
LIMIT 1
`

type GetCallerPoolGrantParams struct {
	CallerID string `json:"caller_id"`
	PoolID   string `json:"pool_id"`
}

func (q *Queries) GetCallerPoolGrant(ctx context.Context, arg GetCallerPoolGrantParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCallerPoolGrant, arg.CallerID, arg.PoolID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getIdentityPoolKind = `-- name: GetIdentityPoolKind :one
SELECT pool_id, kind
FROM identities
WHERE id = ?1
`

type GetIdentityPoolKindRow struct {
	PoolID string `json:"pool_id"`
	Kind   string `json:"kind"`
}

func (q *Queries) GetIdentityPoolKind(ctx context.Context, id string) (GetIdentityPoolKindRow, error) {
	row := q.db.QueryRowContext(ctx, getIdentityPoolKind, id)
	var i GetIdentityPoolKindRow
	err := row.Scan(&i.PoolID, &i.Kind)
	return i, err
}

const getOAuthState = `-- name: GetOAuthState :one
SELECT next_path
FROM oauth_states
WHERE state_hash = ?1
  AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetOAuthState(ctx context.Context, stateHash string) (string, error) {
	row := q.db.QueryRowContext(ctx, getOAuthState, stateHash)
	var next_path string
	err := row.Scan(&next_path)
	return next_path, err
}

const getPoolPolicy = `-- name: GetPoolPolicy :one
SELECT policy_json
FROM pools
WHERE id = ?1
`

func (q *Queries) GetPoolPolicy(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPoolPolicy, id)
	var policy_json string
	err := row.Scan(&policy_json)
	return policy_json, err
}

const getWebSession = `-- name: GetWebSession :one
SELECT
  callers.id,
  callers.name,
  callers.github_login,
  callers.org_login,
  callers.org_verified_at,
  callers.dashboard_role,
  web_sessions.expires_at
FROM web_sessions
JOIN callers ON callers.id = web_sessions.caller_id
WHERE web_sessions.session_hash = ?1
  AND web_sessions.expires_at > CURRENT_TIMESTAMP
  AND callers.status = 'active'
  AND callers.org_login = ?2
`

type GetWebSessionParams struct {
	SessionHash string `json:"session_hash"`
	OrgLogin    string `json:"org_login"`
}

type GetWebSessionRow struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	GithubLogin   string         `json:"github_login"`
	OrgLogin      string         `json:"org_login"`
	OrgVerifiedAt sql.NullString `json:"org_verified_at"`
	DashboardRole string         `json:"dashboard_role"`
	ExpiresAt     string         `json:"expires_at"`
}

func (q *Queries) GetWebSession(ctx context.Context, arg GetWebSessionParams) (GetWebSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getWebSession, arg.SessionHash, arg.OrgLogin)
	var i GetWebSessionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GithubLogin,
		&i.OrgLogin,
		&i.OrgVerifiedAt,
		&i.DashboardRole,
		&i.ExpiresAt,
	)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_events
  (request_id, caller_id, pool_id, route_key, route_kind, identity_id, status, error_code, duration_ms, cache_status, cacheable)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)
`

type InsertAuditParams struct {
	RequestID   string         `json:"request_id"`
	CallerID    string         `json:"caller_id"`
	PoolID      string         `json:"pool_id"`
	RouteKey    string         `json:"route_key"`
	RouteKind   string         `json:"route_kind"`
	IdentityID  sql.NullString `json:"identity_id"`
	Status      int64          `json:"status"`
	ErrorCode   sql.NullString `json:"error_code"`
	DurationMs  int64          `json:"duration_ms"`
	CacheStatus string         `json:"cache_status"`
	Cacheable   int64          `json:"cacheable"`
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertAudit,
		arg.RequestID,
		arg.CallerID,
		arg.PoolID,
		arg.RouteKey,
		arg.RouteKind,
		arg.IdentityID,
		arg.Status,
		arg.ErrorCode,
		arg.DurationMs,
		arg.CacheStatus,
		arg.Cacheable,
	)
	return err
}

const insertCaller = `-- name: InsertCaller :exec
INSERT INTO callers (id, name, token_hash, github_login, github_user_id, org_login, org_verified_at, status)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, 'active')
`

type InsertCallerParams struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	TokenHash     string         `json:"token_hash"`
	GithubLogin   string         `json:"github_login"`
	GithubUserID  sql.NullInt64  `json:"github_user_id"`
	OrgLogin      string         `json:"org_login"`
	OrgVerifiedAt sql.NullString `json:"org_verified_at"`
}

func (q *Queries) InsertCaller(ctx context.Context, arg InsertCallerParams) error {
	_, err := q.db.ExecContext(ctx, insertCaller,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.GithubLogin,
		arg.GithubUserID,
		arg.OrgLogin,
		arg.OrgVerifiedAt,
	)
	return err
}

const insertCallerPool = `-- name: InsertCallerPool :exec
INSERT INTO caller_pools (caller_id, pool_id)
VALUES (?1, ?2)
`

type InsertCallerPoolParams struct {
	CallerID string `json:"caller_id"`
	PoolID   string `json:"pool_id"`
}

func (q *Queries) InsertCallerPool(ctx context.Context, arg InsertCallerPoolParams) error {
	_, err := q.db.ExecContext(ctx, insertCallerPool, arg.CallerID, arg.PoolID)
	return err
}

const insertIdentityScope = `-- name: InsertIdentityScope :exec
INSERT INTO identity_scopes (identity_id, owner, repo, permission, allow_private)
VALUES (?1, ?2, ?3, 'read', ?4)
`

type InsertIdentityScopeParams struct {
	IdentityID   string         `json:"identity_id"`
	Owner        string         `json:"owner"`
	Repo         sql.NullString `json:"repo"`
	AllowPrivate int64          `json:"allow_private"`
}

func (q *Queries) InsertIdentityScope(ctx context.Context, arg InsertIdentityScopeParams) error {
	_, err := q.db.ExecContext(ctx, insertIdentityScope,
		arg.IdentityID,
		arg.Owner,
		arg.Repo,
		arg.AllowPrivate,
	)
	return err
}

const insertOAuthState = `-- name: InsertOAuthState :exec
INSERT INTO oauth_states (state_hash, next_path, expires_at)
VALUES (?1, ?2, datetime(CURRENT_TIMESTAMP, ?3))
`

type InsertOAuthStateParams struct {
	StateHash string      `json:"state_hash"`
	NextPath  string      `json:"next_path"`
	Datetime  interface{} `json:"datetime"`
}

func (q *Queries) InsertOAuthState(ctx context.Context, arg InsertOAuthStateParams) error {
	_, err := q.db.ExecContext(ctx, insertOAuthState, arg.StateHash, arg.NextPath, arg.Datetime)
	return err
}

const insertWebSession = `-- name: InsertWebSession :exec
INSERT INTO web_sessions (session_hash, caller_id, expires_at)
VALUES (?1, ?2, ?3)
`

type InsertWebSessionParams struct {
	SessionHash string `json:"session_hash"`
	CallerID    string `json:"caller_id"`
	ExpiresAt   string `json:"expires_at"`
}

func (q *Queries) InsertWebSession(ctx context.Context, arg InsertWebSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertWebSession, arg.SessionHash, arg.CallerID, arg.ExpiresAt)
	return err
}

const listActiveIdentitiesForPool = `-- name: ListActiveIdentitiesForPool :many
SELECT id, kind, login, secret_ref, installation_id, weight
FROM identities
WHERE pool_id = ?1
  AND status = 'active'
`

type ListActiveIdentitiesForPoolRow struct {
	ID             string        `json:"id"`
	Kind           string        `json:"kind"`
	Login          string        `json:"login"`
	SecretRef      string        `json:"secret_ref"`
	InstallationID sql.NullInt64 `json:"installation_id"`
	Weight         int64         `json:"weight"`
}

func (q *Queries) ListActiveIdentitiesForPool(ctx context.Context, poolID string) ([]ListActiveIdentitiesForPoolRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveIdentitiesForPool, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveIdentitiesForPoolRow
	for rows.Next() {
		var i ListActiveIdentitiesForPoolRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Login,
			&i.SecretRef,
			&i.InstallationID,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveIdentitiesForRoute = `-- name: ListActiveIdentitiesForRoute :many
SELECT DISTINCT identities.id, identities.kind, identities.login, identities.secret_ref, identities.installation_id, identities.weight
FROM identities
JOIN identity_scopes ON identity_scopes.identity_id = identities.id
WHERE identities.pool_id = ?1
  AND identities.status = 'active'
  AND lower(identity_scopes.owner) = lower(?2)
  AND (
    lower(identity_scopes.repo) = lower(?3)
    OR identity_scopes.repo IS NULL
  )
`

type ListActiveIdentitiesForRouteParams struct {
	PoolID  string `json:"pool_id"`
	LOWER   string `json:"LOWER"`
	LOWER_2 string `json:"LOWER_2"`
}

type ListActiveIdentitiesForRouteRow struct {
	ID             string        `json:"id"`
	Kind           string        `json:"kind"`
	Login          string        `json:"login"`
	SecretRef      string        `json:"secret_ref"`
	InstallationID sql.NullInt64 `json:"installation_id"`
	Weight         int64         `json:"weight"`
}

func (q *Queries) ListActiveIdentitiesForRoute(ctx context.Context, arg ListActiveIdentitiesForRouteParams) ([]ListActiveIdentitiesForRouteRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveIdentitiesForRoute, arg.PoolID, arg.LOWER, arg.LOWER_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveIdentitiesForRouteRow
	for rows.Next() {
		var i ListActiveIdentitiesForRouteRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Login,
			&i.SecretRef,
			&i.InstallationID,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loginExistingCaller = `-- name: LoginExistingCaller :one
SELECT callers.id
FROM callers
JOIN caller_pools ON caller_pools.caller_id = callers.id
WHERE callers.github_user_id = ?1
  AND callers.org_login = ?2
  AND callers.status = 'active'
  AND caller_pools.pool_id = ?3
LIMIT 1
`

type LoginExistingCallerParams struct {
	GithubUserID sql.NullInt64 `json:"github_user_id"`
	OrgLogin     string        `json:"org_login"`
	PoolID       string        `json:"pool_id"`
}

func (q *Queries) LoginExistingCaller(ctx context.Context, arg LoginExistingCallerParams) (string, error) {
	row := q.db.QueryRowContext(ctx, loginExistingCaller, arg.GithubUserID, arg.OrgLogin, arg.PoolID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const poolHealth = `-- name: PoolHealth :one
SELECT
  COUNT(*) AS identities_total,
  SUM(CASE WHEN status = 'active' THEN 1 ELSE 0 END) AS identities_healthy
FROM identities
WHERE pool_id = ?1
`

type PoolHealthRow struct {
	IdentitiesTotal   int64           `json:"identities_total"`
	IdentitiesHealthy sql.NullFloat64 `json:"identities_healthy"`
}

func (q *Queries) PoolHealth(ctx context.Context, poolID string) (PoolHealthRow, error) {
	row := q.db.QueryRowContext(ctx, poolHealth, poolID)
	var i PoolHealthRow
	err := row.Scan(&i.IdentitiesTotal, &i.IdentitiesHealthy)
	return i, err
}

const readGitHubCache = `-- name: ReadGitHubCache :one
SELECT status, response_headers_json, body_json, body_encoding, identity_id, identity_kind, created_at
FROM github_cache_entries
WHERE cache_key = ?1
  AND expires_at > CURRENT_TIMESTAMP
`

type ReadGitHubCacheRow struct {
	Status              int64          `json:"status"`
	ResponseHeadersJson string         `json:"response_headers_json"`
	BodyJson            string         `json:"body_json"`
	BodyEncoding        string         `json:"body_encoding"`
	IdentityID          sql.NullString `json:"identity_id"`
	IdentityKind        sql.NullString `json:"identity_kind"`
	CreatedAt           string         `json:"created_at"`
}

func (q *Queries) ReadGitHubCache(ctx context.Context, cacheKey string) (ReadGitHubCacheRow, error) {
	row := q.db.QueryRowContext(ctx, readGitHubCache, cacheKey)
	var i ReadGitHubCacheRow
	err := row.Scan(
		&i.Status,
		&i.ResponseHeadersJson,
		&i.BodyJson,
		&i.BodyEncoding,
		&i.IdentityID,
		&i.IdentityKind,
		&i.CreatedAt,
	)
	return i, err
}

const statsAggregateCaller = `-- name: StatsAggregateCaller :one
SELECT
  COUNT(*) AS requests,
  SUM(CASE WHEN status >= 400 THEN 1 ELSE 0 END) AS errors,
  AVG(duration_ms) AS avg_duration_ms,
  SUM(CASE WHEN cache_status = 'hit' THEN 1 ELSE 0 END) AS cache_hits,
  SUM(CASE WHEN cache_status = 'miss' THEN 1 ELSE 0 END) AS cache_misses,
  SUM(CASE WHEN cache_status = 'bypass' THEN 1 ELSE 0 END) AS cache_bypass,
  SUM(CASE WHEN cache_status = 'unknown' THEN 1 ELSE 0 END) AS cache_unknown,
  SUM(CASE WHEN cacheable = 1 THEN 1 ELSE 0 END) AS cacheable_requests
FROM audit_events
WHERE pool_id = ?1
  AND created_at >= datetime('now', ?2)
  AND caller_id = ?3
`

type StatsAggregateCallerParams struct {
	PoolID   string      `json:"pool_id"`
	Datetime interface{} `json:"datetime"`
	CallerID string      `json:"caller_id"`
}

type StatsAggregateCallerRow struct {
	Requests          int64           `json:"requests"`
	Errors            sql.NullFloat64 `json:"errors"`
	AvgDurationMs     sql.NullFloat64 `json:"avg_duration_ms"`
	CacheHits         sql.NullFloat64 `json:"cache_hits"`
	CacheMisses       sql.NullFloat64 `json:"cache_misses"`
	CacheBypass       sql.NullFloat64 `json:"cache_bypass"`
	CacheUnknown      sql.NullFloat64 `json:"cache_unknown"`
	CacheableRequests sql.NullFloat64 `json:"cacheable_requests"`
}

func (q *Queries) StatsAggregateCaller(ctx context.Context, arg StatsAggregateCallerParams) (StatsAggregateCallerRow, error) {
	row := q.db.QueryRowContext(ctx, statsAggregateCaller, arg.PoolID, arg.Datetime, arg.CallerID)
	var i StatsAggregateCallerRow
	err := row.Scan(
		&i.Requests,
		&i.Errors,
		&i.AvgDurationMs,
		&i.CacheHits,
		&i.CacheMisses,
		&i.CacheBypass,
		&i.CacheUnknown,
		&i.CacheableRequests,
	)
	return i, err
}

const statsAggregatePool = `-- name: StatsAggregatePool :one
SELECT
  COUNT(*) AS requests,
  SUM(CASE WHEN status >= 400 THEN 1 ELSE 0 END) AS errors,
  AVG(duration_ms) AS avg_duration_ms,
  SUM(CASE WHEN cache_status = 'hit' THEN 1 ELSE 0 END) AS cache_hits,
  SUM(CASE WHEN cache_status = 'miss' THEN 1 ELSE 0 END) AS cache_misses,
  SUM(CASE WHEN cache_status = 'bypass' THEN 1 ELSE 0 END) AS cache_bypass,
  SUM(CASE WHEN cache_status = 'unknown' THEN 1 ELSE 0 END) AS cache_unknown,
  SUM(CASE WHEN cacheable = 1 THEN 1 ELSE 0 END) AS cacheable_requests
FROM audit_events
WHERE pool_id = ?1
  AND created_at >= datetime('now', ?2)
`

type StatsAggregatePoolParams struct {
	PoolID   string      `json:"pool_id"`
	Datetime interface{} `json:"datetime"`
}

type StatsAggregatePoolRow struct {
	Requests          int64           `json:"requests"`
	Errors            sql.NullFloat64 `json:"errors"`
	AvgDurationMs     sql.NullFloat64 `json:"avg_duration_ms"`
	CacheHits         sql.NullFloat64 `json:"cache_hits"`
	CacheMisses       sql.NullFloat64 `json:"cache_misses"`
	CacheBypass       sql.NullFloat64 `json:"cache_bypass"`
	CacheUnknown      sql.NullFloat64 `json:"cache_unknown"`
	CacheableRequests sql.NullFloat64 `json:"cacheable_requests"`
}

func (q *Queries) StatsAggregatePool(ctx context.Context, arg StatsAggregatePoolParams) (StatsAggregatePoolRow, error) {
	row := q.db.QueryRowContext(ctx, statsAggregatePool, arg.PoolID, arg.Datetime)
	var i StatsAggregatePoolRow
	err := row.Scan(
		&i.Requests,
		&i.Errors,
		&i.AvgDurationMs,
		&i.CacheHits,
		&i.CacheMisses,
		&i.CacheBypass,
		&i.CacheUnknown,
		&i.CacheableRequests,
	)
	return i, err
}

const statsCacheTotals = `-- name: StatsCacheTotals :one
SELECT
  COUNT(*) AS total_entries,
  SUM(CASE WHEN expires_at > CURRENT_TIMESTAMP THEN 1 ELSE 0 END) AS fresh_entries,
  SUM(CASE WHEN expires_at <= CURRENT_TIMESTAMP THEN 1 ELSE 0 END) AS expired_entries,
  COALESCE(SUM(length(body_json)), 0) AS body_bytes
FROM github_cache_entries
WHERE pool_id = ?1
`

type StatsCacheTotalsRow struct {
	TotalEntries   int64           `json:"total_entries"`
	FreshEntries   sql.NullFloat64 `json:"fresh_entries"`
	ExpiredEntries sql.NullFloat64 `json:"expired_entries"`
	BodyBytes      interface{}     `json:"body_bytes"`
}

func (q *Queries) StatsCacheTotals(ctx context.Context, poolID string) (StatsCacheTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, statsCacheTotals, poolID)
	var i StatsCacheTotalsRow
	err := row.Scan(
		&i.TotalEntries,
		&i.FreshEntries,
		&i.ExpiredEntries,
		&i.BodyBytes,
	)
	return i, err
}

const statsRoutesCaller = `-- name: StatsRoutesCaller :many
SELECT
  route_kind,
  COUNT(*) AS requests,
  SUM(CASE WHEN status >= 400 THEN 1 ELSE 0 END) AS errors,
  AVG(duration_ms) AS avg_duration_ms,
  SUM(CASE WHEN cache_status = 'hit' THEN 1 ELSE 0 END) AS cache_hits,
  SUM(CASE WHEN cache_status = 'miss' THEN 1 ELSE 0 END) AS cache_misses,
  SUM(CASE WHEN cache_status = 'bypass' THEN 1 ELSE 0 END) AS cache_bypass,
  SUM(CASE WHEN cache_status = 'unknown' THEN 1 ELSE 0 END) AS cache_unknown,
  SUM(CASE WHEN cacheable = 1 THEN 1 ELSE 0 END) AS cacheable_requests,
  MAX(created_at) AS latest_seen_at
FROM audit_events
WHERE pool_id = ?1
  AND created_at >= datetime('now', ?2)
  AND caller_id = ?3
GROUP BY route_kind
ORDER BY requests DESC, route_kind
LIMIT 12
`

type StatsRoutesCallerParams struct {
	PoolID   string      `json:"pool_id"`
	Datetime interface{} `json:"datetime"`
	CallerID string      `json:"caller_id"`
}

type StatsRoutesCallerRow struct {
	RouteKind         string          `json:"route_kind"`
	Requests          int64           `json:"requests"`
	Errors            sql.NullFloat64 `json:"errors"`
	AvgDurationMs     sql.NullFloat64 `json:"avg_duration_ms"`
	CacheHits         sql.NullFloat64 `json:"cache_hits"`
	CacheMisses       sql.NullFloat64 `json:"cache_misses"`
	CacheBypass       sql.NullFloat64 `json:"cache_bypass"`
	CacheUnknown      sql.NullFloat64 `json:"cache_unknown"`
	CacheableRequests sql.NullFloat64 `json:"cacheable_requests"`
	LatestSeenAt      interface{}     `json:"latest_seen_at"`
}

func (q *Queries) StatsRoutesCaller(ctx context.Context, arg StatsRoutesCallerParams) ([]StatsRoutesCallerRow, error) {
	rows, err := q.db.QueryContext(ctx, statsRoutesCaller, arg.PoolID, arg.Datetime, arg.CallerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsRoutesCallerRow
	for rows.Next() {
		var i StatsRoutesCallerRow
		if err := rows.Scan(
			&i.RouteKind,
			&i.Requests,
			&i.Errors,
			&i.AvgDurationMs,
			&i.CacheHits,
			&i.CacheMisses,
			&i.CacheBypass,
			&i.CacheUnknown,
			&i.CacheableRequests,
			&i.LatestSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsRoutesPool = `-- name: StatsRoutesPool :many
SELECT
  route_kind,
  COUNT(*) AS requests,
  SUM(CASE WHEN status >= 400 THEN 1 ELSE 0 END) AS errors,
  AVG(duration_ms) AS avg_duration_ms,
  SUM(CASE WHEN cache_status = 'hit' THEN 1 ELSE 0 END) AS cache_hits,
  SUM(CASE WHEN cache_status = 'miss' THEN 1 ELSE 0 END) AS cache_misses,
  SUM(CASE WHEN cache_status = 'bypass' THEN 1 ELSE 0 END) AS cache_bypass,
  SUM(CASE WHEN cache_status = 'unknown' THEN 1 ELSE 0 END) AS cache_unknown,
  SUM(CASE WHEN cacheable = 1 THEN 1 ELSE 0 END) AS cacheable_requests,
  MAX(created_at) AS latest_seen_at
FROM audit_events
WHERE pool_id = ?1
  AND created_at >= datetime('now', ?2)
GROUP BY route_kind
ORDER BY requests DESC, route_kind
LIMIT 12
`

type StatsRoutesPoolParams struct {
	PoolID   string      `json:"pool_id"`
	Datetime interface{} `json:"datetime"`
}

type StatsRoutesPoolRow struct {
	RouteKind         string          `json:"route_kind"`
	Requests          int64           `json:"requests"`
	Errors            sql.NullFloat64 `json:"errors"`
	AvgDurationMs     sql.NullFloat64 `json:"avg_duration_ms"`
	CacheHits         sql.NullFloat64 `json:"cache_hits"`
	CacheMisses       sql.NullFloat64 `json:"cache_misses"`
	CacheBypass       sql.NullFloat64 `json:"cache_bypass"`
	CacheUnknown      sql.NullFloat64 `json:"cache_unknown"`
	CacheableRequests sql.NullFloat64 `json:"cacheable_requests"`
	LatestSeenAt      interface{}     `json:"latest_seen_at"`
}

func (q *Queries) StatsRoutesPool(ctx context.Context, arg StatsRoutesPoolParams) ([]StatsRoutesPoolRow, error) {
	rows, err := q.db.QueryContext(ctx, statsRoutesPool, arg.PoolID, arg.Datetime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsRoutesPoolRow
	for rows.Next() {
		var i StatsRoutesPoolRow
		if err := rows.Scan(
			&i.RouteKind,
			&i.Requests,
			&i.Errors,
			&i.AvgDurationMs,
			&i.CacheHits,
			&i.CacheMisses,
			&i.CacheBypass,
			&i.CacheUnknown,
			&i.CacheableRequests,
			&i.LatestSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchWebSession = `-- name: TouchWebSession :exec
UPDATE web_sessions
SET last_seen_at = CURRENT_TIMESTAMP
WHERE session_hash = ?1
`

func (q *Queries) TouchWebSession(ctx context.Context, sessionHash string) error {
	_, err := q.db.ExecContext(ctx, touchWebSession, sessionHash)
	return err
}

const updateCallerLogin = `-- name: UpdateCallerLogin :exec
UPDATE callers
SET name = ?1,
    token_hash = ?2,
    github_login = ?3,
    github_user_id = ?4,
    org_verified_at = ?5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?6
`

type UpdateCallerLoginParams struct {
	Name          string         `json:"name"`
	TokenHash     string         `json:"token_hash"`
	GithubLogin   string         `json:"github_login"`
	GithubUserID  sql.NullInt64  `json:"github_user_id"`
	OrgVerifiedAt sql.NullString `json:"org_verified_at"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateCallerLogin(ctx context.Context, arg UpdateCallerLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateCallerLogin,
		arg.Name,
		arg.TokenHash,
		arg.GithubLogin,
		arg.GithubUserID,
		arg.OrgVerifiedAt,
		arg.ID,
	)
	return err
}

const updateCallerOrgVerifiedAt = `-- name: UpdateCallerOrgVerifiedAt :exec
UPDATE callers
SET org_verified_at = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type UpdateCallerOrgVerifiedAtParams struct {
	OrgVerifiedAt sql.NullString `json:"org_verified_at"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateCallerOrgVerifiedAt(ctx context.Context, arg UpdateCallerOrgVerifiedAtParams) error {
	_, err := q.db.ExecContext(ctx, updateCallerOrgVerifiedAt, arg.OrgVerifiedAt, arg.ID)
	return err
}

const updateCallerWebLogin = `-- name: UpdateCallerWebLogin :exec
UPDATE callers
SET name = ?1,
    github_login = ?2,
    github_user_id = ?3,
    org_verified_at = ?4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?5
`

type UpdateCallerWebLoginParams struct {
	Name          string         `json:"name"`
	GithubLogin   string         `json:"github_login"`
	GithubUserID  sql.NullInt64  `json:"github_user_id"`
	OrgVerifiedAt sql.NullString `json:"org_verified_at"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateCallerWebLogin(ctx context.Context, arg UpdateCallerWebLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateCallerWebLogin,
		arg.Name,
		arg.GithubLogin,
		arg.GithubUserID,
		arg.OrgVerifiedAt,
		arg.ID,
	)
	return err
}

const upsertIdentity = `-- name: UpsertIdentity :exec
INSERT INTO identities (id, pool_id, kind, login, secret_ref, installation_id, status, weight)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, 'active', ?7)
ON CONFLICT(id) DO UPDATE SET
  login = excluded.login,
  secret_ref = excluded.secret_ref,
  installation_id = excluded.installation_id,
  status = 'active',
  weight = excluded.weight,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertIdentityParams struct {
	ID             string        `json:"id"`
	PoolID         string        `json:"pool_id"`
	Kind           string        `json:"kind"`
	Login          string        `json:"login"`
	SecretRef      string        `json:"secret_ref"`
	InstallationID sql.NullInt64 `json:"installation_id"`
	Weight         int64         `json:"weight"`
}

func (q *Queries) UpsertIdentity(ctx context.Context, arg UpsertIdentityParams) error {
	_, err := q.db.ExecContext(ctx, upsertIdentity,
		arg.ID,
		arg.PoolID,
		arg.Kind,
		arg.Login,
		arg.SecretRef,
		arg.InstallationID,
		arg.Weight,
	)
	return err
}

const upsertPublicRepoProof = `-- name: UpsertPublicRepoProof :exec
INSERT INTO github_public_repos (owner, repo, checked_at, expires_at)
VALUES (?1, ?2, CURRENT_TIMESTAMP, datetime(CURRENT_TIMESTAMP, ?3))
ON CONFLICT(owner, repo) DO UPDATE SET
  checked_at = excluded.checked_at,
  expires_at = excluded.expires_at
`

type UpsertPublicRepoProofParams struct {
	Owner    string      `json:"owner"`
	Repo     string      `json:"repo"`
	Datetime interface{} `json:"datetime"`
}

func (q *Queries) UpsertPublicRepoProof(ctx context.Context, arg UpsertPublicRepoProofParams) error {
	_, err := q.db.ExecContext(ctx, upsertPublicRepoProof, arg.Owner, arg.Repo, arg.Datetime)
	return err
}

const webLoginCaller = `-- name: WebLoginCaller :one
SELECT callers.id, callers.dashboard_role
FROM callers
JOIN caller_pools ON caller_pools.caller_id = callers.id
WHERE callers.github_user_id = ?1
  AND callers.org_login = ?2
  AND callers.status = 'active'
  AND caller_pools.pool_id = ?3
LIMIT 1
`

type WebLoginCallerParams struct {
	GithubUserID sql.NullInt64 `json:"github_user_id"`
	OrgLogin     string        `json:"org_login"`
	PoolID       string        `json:"pool_id"`
}

type WebLoginCallerRow struct {
	ID            string `json:"id"`
	DashboardRole string `json:"dashboard_role"`
}

func (q *Queries) WebLoginCaller(ctx context.Context, arg WebLoginCallerParams) (WebLoginCallerRow, error) {
	row := q.db.QueryRowContext(ctx, webLoginCaller, arg.GithubUserID, arg.OrgLogin, arg.PoolID)
	var i WebLoginCallerRow
	err := row.Scan(&i.ID, &i.DashboardRole)
	return i, err
}

const writeGitHubCache = `-- name: WriteGitHubCache :exec
INSERT INTO github_cache_entries
  (cache_key, pool_id, method, path, query_json, headers_json, route_key, route_kind,
   status, response_headers_json, body_json, body_encoding, identity_id, identity_kind, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15)
ON CONFLICT(cache_key) DO UPDATE SET
  status = excluded.status,
  response_headers_json = excluded.response_headers_json,
  body_json = excluded.body_json,
  body_encoding = excluded.body_encoding,
  identity_id = excluded.identity_id,
  identity_kind = excluded.identity_kind,
  created_at = CURRENT_TIMESTAMP,
  expires_at = excluded.expires_at
`

type WriteGitHubCacheParams struct {
	CacheKey            string         `json:"cache_key"`
	PoolID              string         `json:"pool_id"`
	Method              string         `json:"method"`
	Path                string         `json:"path"`
	QueryJson           string         `json:"query_json"`
	HeadersJson         string         `json:"headers_json"`
	RouteKey            string         `json:"route_key"`
	RouteKind           string         `json:"route_kind"`
	Status              int64          `json:"status"`
	ResponseHeadersJson string         `json:"response_headers_json"`
	BodyJson            string         `json:"body_json"`
	BodyEncoding        string         `json:"body_encoding"`
	IdentityID          sql.NullString `json:"identity_id"`
	IdentityKind        sql.NullString `json:"identity_kind"`
	ExpiresAt           string         `json:"expires_at"`
}

func (q *Queries) WriteGitHubCache(ctx context.Context, arg WriteGitHubCacheParams) error {
	_, err := q.db.ExecContext(ctx, writeGitHubCache,
		arg.CacheKey,
		arg.PoolID,
		arg.Method,
		arg.Path,
		arg.QueryJson,
		arg.HeadersJson,
		arg.RouteKey,
		arg.RouteKind,
		arg.Status,
		arg.ResponseHeadersJson,
		arg.BodyJson,
		arg.BodyEncoding,
		arg.IdentityID,
		arg.IdentityKind,
		arg.ExpiresAt,
	)
	return err
}
