// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbquery

import (
	"database/sql"
)

type AuditEvent struct {
	RequestID   string         `json:"request_id"`
	CallerID    string         `json:"caller_id"`
	PoolID      string         `json:"pool_id"`
	RouteKey    string         `json:"route_key"`
	RouteKind   string         `json:"route_kind"`
	IdentityID  sql.NullString `json:"identity_id"`
	Status      int64          `json:"status"`
	ErrorCode   sql.NullString `json:"error_code"`
	CreatedAt   string         `json:"created_at"`
	DurationMs  int64          `json:"duration_ms"`
	CacheStatus string         `json:"cache_status"`
	Cacheable   int64          `json:"cacheable"`
}

type Caller struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	TokenHash     string         `json:"token_hash"`
	GithubLogin   string         `json:"github_login"`
	OrgLogin      string         `json:"org_login"`
	OrgVerifiedAt sql.NullString `json:"org_verified_at"`
	Status        string         `json:"status"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
	GithubUserID  sql.NullInt64  `json:"github_user_id"`
	DashboardRole string         `json:"dashboard_role"`
}

type CallerPool struct {
	CallerID  string `json:"caller_id"`
	PoolID    string `json:"pool_id"`
	CreatedAt string `json:"created_at"`
}

type Cooldown struct {
	IdentityID string `json:"identity_id"`
	RouteKey   string `json:"route_key"`
	Status     int64  `json:"status"`
	Reason     string `json:"reason"`
	ExpiresAt  int64  `json:"expires_at"`
}

type GithubCacheEntry struct {
	CacheKey            string         `json:"cache_key"`
	PoolID              string         `json:"pool_id"`
	Method              string         `json:"method"`
	Path                string         `json:"path"`
	QueryJson           string         `json:"query_json"`
	HeadersJson         string         `json:"headers_json"`
	RouteKey            string         `json:"route_key"`
	RouteKind           string         `json:"route_kind"`
	Status              int64          `json:"status"`
	ResponseHeadersJson string         `json:"response_headers_json"`
	BodyJson            string         `json:"body_json"`
	BodyEncoding        string         `json:"body_encoding"`
	IdentityID          sql.NullString `json:"identity_id"`
	IdentityKind        sql.NullString `json:"identity_kind"`
	CreatedAt           string         `json:"created_at"`
	ExpiresAt           string         `json:"expires_at"`
}

type GithubPublicRepo struct {
	Owner     string `json:"owner"`
	Repo      string `json:"repo"`
	CheckedAt string `json:"checked_at"`
	ExpiresAt string `json:"expires_at"`
}

type Identity struct {
	ID             string        `json:"id"`
	PoolID         string        `json:"pool_id"`
	Kind           string        `json:"kind"`
	Login          string        `json:"login"`
	SecretRef      string        `json:"secret_ref"`
	Status         string        `json:"status"`
	Weight         int64         `json:"weight"`
	CreatedAt      string        `json:"created_at"`
	UpdatedAt      string        `json:"updated_at"`
	InstallationID sql.NullInt64 `json:"installation_id"`
}

type IdentityScope struct {
	IdentityID   string         `json:"identity_id"`
	Owner        string         `json:"owner"`
	Repo         sql.NullString `json:"repo"`
	Permission   string         `json:"permission"`
	AllowPrivate int64          `json:"allow_private"`
	CreatedAt    string         `json:"created_at"`
}

type Lease struct {
	RouteKey   string `json:"route_key"`
	IdentityID string `json:"identity_id"`
	ExpiresAt  int64  `json:"expires_at"`
}

type OauthState struct {
	StateHash string `json:"state_hash"`
	NextPath  string `json:"next_path"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

type Pool struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	PolicyJson string `json:"policy_json"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type RateState struct {
	IdentityID string `json:"identity_id"`
	Resource   string `json:"resource"`
	Remaining  int64  `json:"remaining"`
	ResetAt    int64  `json:"reset_at"`
}

type WebSession struct {
	SessionHash string `json:"session_hash"`
	CallerID    string `json:"caller_id"`
	CreatedAt   string `json:"created_at"`
	LastSeenAt  string `json:"last_seen_at"`
	ExpiresAt   string `json:"expires_at"`
}
