import { readFile, writeFile } from "node:fs/promises";
import { PUBLIC_SHAPES } from "../src/github-public-shapes.ts";
import { ROUTES } from "../src/route-manifest.ts";

const outputPath = new URL("../cmd/octopool/routes_generated.go", import.meta.url);
const seenPatterns = new Set();
const patterns = ROUTES.map((route) => {
  if (seenPatterns.has(route.pattern.source)) {
    throw new Error(`Duplicate route pattern: ${route.pattern.source}`);
  }
  seenPatterns.add(route.pattern.source);
  const pattern = route.pattern.source.replaceAll("\\/", "/").replaceAll(/\(\?<[^>]+>/g, "(?:");
  if (pattern.includes("`")) {
    throw new Error(`Route pattern cannot contain a backtick: ${pattern}`);
  }
  return pattern;
});

const lines = [
  "// Code generated by scripts/generate-routes.mjs from src/route-manifest.ts; DO NOT EDIT.",
  "",
  "package main",
  "",
  'import "regexp"',
  "",
  "const (",
  ...Object.entries(PUBLIC_SHAPES).map(
    ([name, value]) =>
      `\tpublicShape${name[0].toUpperCase()}${name.slice(1)} = ${JSON.stringify(value)}`,
  ),
  ")",
  "",
  "var relayQueryPathPatterns = []*regexp.Regexp{",
  ...patterns.map((pattern) => `\tregexp.MustCompile(\`${pattern}\`),`),
  "}",
  "",
];

const outputs = [
  [outputPath, lines.join("\n")],
  await renderSection(
    new URL("../docs/relay.md", import.meta.url),
    "supported-route-kinds",
    [...new Set(ROUTES.map((route) => route.kind))].map((kind) => `- \`${kind}\``).join("\n"),
  ),
  await renderSection(
    new URL("../docs/token-free.md", import.meta.url),
    "token-free-api-routes",
    [
      "```text",
      ...ROUTES.filter(
        (route) => route.capabilities.publicApi || route.capabilities.fallback !== "pool",
      ).map((route) => `GET ${docsTemplate(route.template)}`),
      "```",
    ].join("\n"),
  ),
];

await Promise.all(outputs.map(([file, output]) => writeFile(file, output)));

async function renderSection(file, name, content) {
  const start = `<!-- ${name}:start -->`;
  const end = `<!-- ${name}:end -->`;
  const input = await readFile(file, "utf8");
  const startIndex = input.indexOf(start);
  const endIndex = input.indexOf(end);
  if (startIndex === -1 || endIndex <= startIndex) {
    throw new Error(`Missing generated section ${name} in ${file.pathname}`);
  }
  const output = `${input.slice(0, startIndex + start.length)}\n\n${content}\n\n${input.slice(endIndex)}`;
  return [file, output];
}

function docsTemplate(template) {
  const names = {
    commitRef: "ref",
    compare: "comparison",
    contentPath: "path",
    gistId: "gist",
    gitRef: "ref",
    readmeDir: "dir",
  };
  return template.replace(/\{([^}]+)\}/g, (_token, name) => `{${names[name] ?? name}}`);
}
