import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const queriesDir = "sql/queries";
const outFile = "src/generated/sql.ts";

const entries = [];
for (const file of (await readdir(queriesDir)).sort()) {
  if (!file.endsWith(".sql")) continue;
  const body = await readFile(path.join(queriesDir, file), "utf8");
  const blocks = body.split(/(?=^-- name:\s+)/m).filter((block) => block.trim() !== "");
  for (const block of blocks) {
    const match = /^-- name:\s+([A-Za-z0-9_]+)\s+:\w+/m.exec(block);
    if (match === null) {
      throw new Error(`${file}: SQL block is missing a sqlc name annotation`);
    }
    const name = lowerFirst(match[1]);
    const sql = block
      .replace(/^-- name:.*\n/, "")
      .trim()
      .replace(/;$/, "")
      .trim();
    entries.push({ name, sql });
  }
}

const seen = new Set();
for (const entry of entries) {
  if (seen.has(entry.name)) {
    throw new Error(`duplicate query name: ${entry.name}`);
  }
  seen.add(entry.name);
}

const lines = [
  "// Code generated by scripts/generate-sql.mjs from sql/queries/*.sql; DO NOT EDIT.",
  "",
  "export const queries = {",
];
for (const entry of entries) {
  lines.push(`  ${entry.name}: ${JSON.stringify(entry.sql)},`);
}
lines.push("} as const;", "", "export type QueryName = keyof typeof queries;", "");

await mkdir(path.dirname(outFile), { recursive: true });
await writeFile(outFile, lines.join("\n"));

function lowerFirst(value) {
  return value.slice(0, 1).toLowerCase() + value.slice(1);
}
